---
variables:
  SITE_URL: community.torproject.org
  TRANSLATION_BRANCH: communitytpo-contentspot

include:
  - project: tpo/tpa/ci-templates
    file:
      - lektor.yml
      - static-shim-deploy.yml
